#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SplitView;
                ref class ListBoxItem;
                ref class Frame;
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}

namespace SmartMachinesRenting
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::SplitView^ HamburgerSplitView;
        private: ::Windows::UI::Xaml::Controls::ListBoxItem^ RentPanel;
        private: ::Windows::UI::Xaml::Controls::ListBoxItem^ AlreadyRentedPanel;
        private: ::Windows::UI::Xaml::Controls::Frame^ MyFrame;
        private: ::Windows::UI::Xaml::Controls::Button^ HomeButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Title;
        private: ::Windows::UI::Xaml::Controls::Button^ SearchIconBorder;
    };
}

