//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::SmartMachinesRenting::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::SmartMachinesRenting::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->HamburgerSplitView = safe_cast<::Windows::UI::Xaml::Controls::SplitView^>(__target);
            }
            break;
        case 2:
            {
                ::Windows::UI::Xaml::Controls::ListBox^ element2 = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(element2))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::SmartMachinesRenting::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::HamburgerListBox_SelectionChanged);
            }
            break;
        case 3:
            {
                this->RentPanel = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
            }
            break;
        case 4:
            {
                this->AlreadyRentedPanel = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
            }
            break;
        case 5:
            {
                this->MyFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
            }
            break;
        case 6:
            {
                this->HomeButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->HomeButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SmartMachinesRenting::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::HomeButton_Click);
            }
            break;
        case 7:
            {
                this->Title = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 8:
            {
                this->SearchIconBorder = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::SmartMachinesRenting::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


