//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "RentedView.xaml.h"

void ::SmartMachinesRenting::RentedView::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///RentedView.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class SmartMachinesRenting::RentedView::RentedView_obj4_Bindings 
    : public ::XamlBindingInfo::XamlBindingsBase<::SmartMachinesRenting::Digger>
{
public:
    RentedView_obj4_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 5:
                this->obj5 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 6:
                this->obj6 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                break;
        }
    }

    void ResetTemplate()
    {
    }

    int ProcessBindings(::Windows::UI::Xaml::Controls::ContainerContentChangingEventArgs^ args)
    {
        int nextPhase = -1;
        switch(args->Phase)
        {
            case 0:
                nextPhase = -1;
                this->SetDataRoot(static_cast<::SmartMachinesRenting::Digger^>(args->Item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    safe_cast<::Windows::UI::Xaml::FrameworkElement^>(args->ItemContainer->ContentTemplateRoot)->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
        }
        this->Update_((::SmartMachinesRenting::Digger^) args->Item, (1 << args->Phase));
        return nextPhase;
    }
private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Controls::TextBlock^ obj5;
    ::Windows::UI::Xaml::Controls::Image^ obj6;

    // Update methods for each path node used in binding steps.
    void Update_(::SmartMachinesRenting::Digger^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Name(obj->Name, phase);
                this->Update_ImgUrl(obj->ImgUrl, phase);
            }
        }
    }
    void Update_Name(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj5, obj, nullptr);
        }
    }
    void Update_ImgUrl(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_Image_Source(this->obj6, (::Windows::UI::Xaml::Media::ImageSource^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Media::ImageSource::typeid, obj), nullptr);
        }
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class SmartMachinesRenting::RentedView::RentedView_obj1_Bindings 
    : public ::XamlBindingInfo::XamlBindingsBase<::SmartMachinesRenting::RentedView>
{
public:
    RentedView_obj1_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 2:
                this->obj2 = safe_cast<::Windows::UI::Xaml::Controls::GridView^>(__target);
                break;
        }
    }
private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Controls::GridView^ obj2;

    // Update methods for each path node used in binding steps.
    void Update_(::SmartMachinesRenting::RentedView^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_RentedMachines(obj->RentedMachines, phase);
            }
        }
    }
    void Update_RentedMachines(::Windows::Foundation::Collections::IVector<::SmartMachinesRenting::Digger^>^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_ItemsControl_ItemsSource(this->obj2, obj, nullptr);
        }
    }
};

void ::SmartMachinesRenting::RentedView::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 2:
            {
                this->MyGridView = safe_cast<::Windows::UI::Xaml::Controls::GridView^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::GridView^>(this->MyGridView))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::SmartMachinesRenting::RentedView::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&RentedView::MyGridView_SelectionChanged);
            }
            break;
        case 3:
            {
                this->DetailFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::SmartMachinesRenting::RentedView::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 1:
            {
                ::Windows::UI::Xaml::Controls::Page^ element1 = safe_cast<::Windows::UI::Xaml::Controls::Page^>(__target);
                RentedView_obj1_Bindings* objBindings = new RentedView_obj1_Bindings();
                objBindings->SetDataRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                this->Bindings = bindings;
                element1->Loading += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Platform::Object^>(bindings, &::XamlBindingInfo::XamlBindings::Loading);
            }
            break;
        case 4:
            {
                ::Windows::UI::Xaml::Controls::StackPanel^ element4 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
                RentedView_obj4_Bindings* objBindings = new RentedView_obj4_Bindings();
                objBindings->SetDataRoot(element4->DataContext);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element4);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element4, bindings);
            }
            break;
    }
    return bindings;
}


